services:
  app:
    build: .
    container_name: onboarding-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - onboarding_net

networks:
  onboarding_net:
    external: true
